### ISSUE TITLE
Unable to compile example in stand-alone repository using main due to Serde error

### ISSUE THREAD

**Issue by quietlychris** [neuronika/neuronika#103]
Hello,

I tried building the `quickstart` example in a stand-alone project today, and was unable to do so. I've tested that cloning `neuronika` off the `main` branch builds (and the example runs), but when pulling it in as a dependency, I am consistently running into the error 
```sh
error[E0277]: the trait bound `NeuralNetwork: serde::de::Deserialize<'_>` is not satisfied
    --> src/main.rs:53:9
     |
53   |     } = serde_json::from_str(
     |         ^^^^^^^^^^^^^^^^^^^^ the trait `serde::de::Deserialize<'_>` is not implemented for `NeuralNetwork`
     |
note: required by a bound in `serde_json::from_str`
    --> /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.79/src/de.rs:2611:8
     |
2611 |     T: de::Deserialize<'a>,
     |        ^^^^^^^^^^^^^^^^^^^ required by this bound in `serde_json::from_str`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `neuronika_example` due to previous error
```
Running this code with `0.2` doesn't seem feasible due to what I'm assuming are updated trait bounds around `Overwrite`.

My `Cargo.toml` file has the following configuration, based on `neuronika` main's:
```toml
[dependencies]
neuronika = {git = "https://github.com/neuronika/neuronika.git", branch = "main", features = ["serialize"]}
ndarray = {version = "0.15.4", features = ["rayon"]}
serde_json = "1.0.72"
serde = {version = "1.0.130", features = ["derive"]}
```
I am compiling with `rustc 1.60.0-stable` on an x86 platform using Pop!_OS 21.04. 

I'm very interested in this library, and would love to experiment with starting to solve basic classification problem like MNIST or CIFAR-10 with it. Any advice on how I might be able to resolve these issues would be greatly appreciated. Thanks for your time!

**Comment by quietlychris** [comment]
I'm afraid it doesn't look like this fixes the issue. Thanks for your consideration, but since it sounds like you're doing a lot of re-factoring at the moment (really looking forward to the features you mentioned landing!), I'll probably just wait until the next release to really start digging in.

**Comment by frjnn** [comment]
How are you running the example? You should be using `cargo run --example quickstart --features="serialize"`

**Comment by quietlychris** [comment]
I think we've had a miscommunication. When I clone the `neuronika` repository and run `cargo run --example quickstart --features="serialize"`, everything compiles fine. 

However, when I create a new repository `cargo new --bin neurnika_test`, copy-paste in the `quickstart` example code, and try to run it while having the following `Cargo.toml` file
```toml
[dependencies]
neuronika = {git = "https://github.com/neuronika/neuronika.git", branch = "main", features = ["serialize"]}
ndarray = {version = "0.15.4", features = ["rayon"]}
serde_json = "1.0.72"
serde = {version = "1.0.130", features = ["derive"]}
```
which should import the `neuronika` main branch with the `serialize` feature enabled, I get a compilation error regarding `serde` trait bounds as seen in my first example. In essence, it seems like in-project development builds are fine, but I am having issues using `neuronika` main as a dependency in other projects.
